################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_ble.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_matter.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_thread.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/custom_stm.c 

C_DEPS += \
./Application/User/STM32_WPAN/app/app_ble.d \
./Application/User/STM32_WPAN/app/app_matter.d \
./Application/User/STM32_WPAN/app/app_thread.d \
./Application/User/STM32_WPAN/app/custom_stm.d 

OBJS += \
./Application/User/STM32_WPAN/app/app_ble.o \
./Application/User/STM32_WPAN/app/app_matter.o \
./Application/User/STM32_WPAN/app/app_thread.o \
./Application/User/STM32_WPAN/app/custom_stm.o 


# Each subdirectory must supply rules for building sources it contributes
Application/User/STM32_WPAN/app/app_ble.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_ble.c Application/User/STM32_WPAN/app/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/STM32_WPAN/app/app_matter.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_matter.c Application/User/STM32_WPAN/app/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/STM32_WPAN/app/app_thread.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/app_thread.c Application/User/STM32_WPAN/app/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/STM32_WPAN/app/custom_stm.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Projects/STM32WB5MM-DK/Applications/Matter/Lighting-App/STM32_WPAN/App/custom_stm.c Application/User/STM32_WPAN/app/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-STM32_WPAN-2f-app

clean-Application-2f-User-2f-STM32_WPAN-2f-app:
	-$(RM) ./Application/User/STM32_WPAN/app/app_ble.cyclo ./Application/User/STM32_WPAN/app/app_ble.d ./Application/User/STM32_WPAN/app/app_ble.o ./Application/User/STM32_WPAN/app/app_ble.su ./Application/User/STM32_WPAN/app/app_matter.cyclo ./Application/User/STM32_WPAN/app/app_matter.d ./Application/User/STM32_WPAN/app/app_matter.o ./Application/User/STM32_WPAN/app/app_matter.su ./Application/User/STM32_WPAN/app/app_thread.cyclo ./Application/User/STM32_WPAN/app/app_thread.d ./Application/User/STM32_WPAN/app/app_thread.o ./Application/User/STM32_WPAN/app/app_thread.su ./Application/User/STM32_WPAN/app/custom_stm.cyclo ./Application/User/STM32_WPAN/app/custom_stm.d ./Application/User/STM32_WPAN/app/custom_stm.o ./Application/User/STM32_WPAN/app/custom_stm.su

.PHONY: clean-Application-2f-User-2f-STM32_WPAN-2f-app

