################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User/Core/Startup \
Application/User/Core/src \
Application/User/STM32_WPAN/app \
Application/User/STM32_WPAN/target \
Drivers/BSP/Components/STM32WB5MM-DK \
Drivers/BSP/Components/s25fl128s \
Drivers/BSP/Components/ssd1315 \
Drivers/STM32WBxx_HAL_Driver \
Middlewares/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/FreeRTOS/Source \
Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/FreeRTOS/Source/portable/MemMang \
Middlewares/STM32_WPAN/ble/core/auto \
Middlewares/STM32_WPAN/ble/core/template \
Middlewares/STM32_WPAN/ble/svc/src \
Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci \
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl \
Middlewares/STM32_WPAN/thread/openthread/core/openthread_api \
Middlewares/STM32_WPAN/utilities \
Middlewares/connectedhomeip/devices/lighting-app/zap-generated \
Middlewares/connectedhomeip/src/access \
Middlewares/connectedhomeip/src/access/examples \
Middlewares/connectedhomeip/src/app \
Middlewares/connectedhomeip/src/app/MessageDef \
Middlewares/connectedhomeip/src/app/app-platform \
Middlewares/connectedhomeip/src/app/clusters/access-control-server \
Middlewares/connectedhomeip/src/app/clusters/administrator-commissioning-server \
Middlewares/connectedhomeip/src/app/clusters/basic-information \
Middlewares/connectedhomeip/src/app/clusters/descriptor \
Middlewares/connectedhomeip/src/app/clusters/diagnostic-logs-server \
Middlewares/connectedhomeip/src/app/clusters/fixed-label-server \
Middlewares/connectedhomeip/src/app/clusters/general-commissioning-server \
Middlewares/connectedhomeip/src/app/clusters/general-diagnostics-server \
Middlewares/connectedhomeip/src/app/clusters/group-key-mgmt-server \
Middlewares/connectedhomeip/src/app/clusters/groups-server \
Middlewares/connectedhomeip/src/app/clusters/identify-server \
Middlewares/connectedhomeip/src/app/clusters/level-control \
Middlewares/connectedhomeip/src/app/clusters/localization-configuration-server \
Middlewares/connectedhomeip/src/app/clusters/network-commissioning \
Middlewares/connectedhomeip/src/app/clusters/on-off-server \
Middlewares/connectedhomeip/src/app/clusters/operational-credentials-server \
Middlewares/connectedhomeip/src/app/clusters/ota-requestor \
Middlewares/connectedhomeip/src/app/clusters/scenes-server \
Middlewares/connectedhomeip/src/app/clusters/software-diagnostics-server \
Middlewares/connectedhomeip/src/app/clusters/thread-network-diagnostics-server \
Middlewares/connectedhomeip/src/app/clusters/time-format-localization-server \
Middlewares/connectedhomeip/src/app/clusters/user-label-server \
Middlewares/connectedhomeip/src/app/data-model \
Middlewares/connectedhomeip/src/app/icd/server \
Middlewares/connectedhomeip/src/app/reporting \
Middlewares/connectedhomeip/src/app/server \
Middlewares/connectedhomeip/src/app/util \
Middlewares/connectedhomeip/src/app-common/zap-generated/attributes \
Middlewares/connectedhomeip/src/app-common/zap-generated \
Middlewares/connectedhomeip/src/ble \
Middlewares/connectedhomeip/src/credentials \
Middlewares/connectedhomeip/src/credentials/examples \
Middlewares/connectedhomeip/src/crypto \
Middlewares/connectedhomeip/src/include/platform/internal \
Middlewares/connectedhomeip/src/inet \
Middlewares/connectedhomeip/src/lib/address_resolve \
Middlewares/connectedhomeip/src/lib/asn1 \
Middlewares/connectedhomeip/src/lib/core \
Middlewares/connectedhomeip/src/lib/dnssd \
Middlewares/connectedhomeip/src/lib/support \
Middlewares/connectedhomeip/src/lib/support/logging \
Middlewares/connectedhomeip/src/lib/support/verhoeff \
Middlewares/connectedhomeip/src/messaging \
Middlewares/connectedhomeip/src/platform \
Middlewares/connectedhomeip/src/platform/FreeRTOS \
Middlewares/connectedhomeip/src/platform/OpenThread \
Middlewares/connectedhomeip/src/platform/logging/impl/stdio \
Middlewares/connectedhomeip/src/platform/stm32 \
Middlewares/connectedhomeip/src/protocols \
Middlewares/connectedhomeip/src/protocols/bdx \
Middlewares/connectedhomeip/src/protocols/echo \
Middlewares/connectedhomeip/src/protocols/interaction_model \
Middlewares/connectedhomeip/src/protocols/secure_channel \
Middlewares/connectedhomeip/src/protocols/user_directed_commissioning \
Middlewares/connectedhomeip/src/setup_payload \
Middlewares/connectedhomeip/src/system \
Middlewares/connectedhomeip/src/transport \
Middlewares/connectedhomeip/src/transport/raw \
Middlewares/mbedtls/library \
Utilities/LCD \
Utilities \

