################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_events.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gap_aci.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gatt_aci.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hal_aci.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hci_le.c \
/Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_l2cap_aci.c 

C_DEPS += \
./Middlewares/STM32_WPAN/ble/core/auto/ble_events.d \
./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.d \
./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.d \
./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.d \
./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.d \
./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.d 

OBJS += \
./Middlewares/STM32_WPAN/ble/core/auto/ble_events.o \
./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.o \
./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.o \
./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.o \
./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.o \
./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_WPAN/ble/core/auto/ble_events.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_events.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gap_aci.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gatt_aci.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hal_aci.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hci_le.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.o: /Users/brady/Downloads/STM32CubeExpansion_MATTER_V1.1.0/Middlewares/ST/STM32_WPAN/ble/core/auto/ble_l2cap_aci.c Middlewares/STM32_WPAN/ble/core/auto/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WB5M_DK -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Middlewares/Third_Party/mbedtls/library -I../../../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_WPAN-2f-ble-2f-core-2f-auto

clean-Middlewares-2f-STM32_WPAN-2f-ble-2f-core-2f-auto:
	-$(RM) ./Middlewares/STM32_WPAN/ble/core/auto/ble_events.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_events.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_events.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_events.su ./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_gap_aci.su ./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_gatt_aci.su ./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_hal_aci.su ./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_hci_le.su ./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.cyclo ./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.d ./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.o ./Middlewares/STM32_WPAN/ble/core/auto/ble_l2cap_aci.su

.PHONY: clean-Middlewares-2f-STM32_WPAN-2f-ble-2f-core-2f-auto

